# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/optimization_guide/proto/common_types.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'components/optimization_guide/proto/common_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6components/optimization_guide/proto/common_types.proto\x12\x18optimization_guide.proto\"3\n\nFieldTrial\x12\x11\n\tname_hash\x18\x01 \x01(\r\x12\x12\n\ngroup_hash\x18\x02 \x01(\r\"*\n\x08\x44uration\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"&\n\x03\x41ny\x12\x10\n\x08type_url\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"Y\n\nOriginInfo\x12\x34\n\x08platform\x18\x01 \x01(\x0e\x32\".optimization_guide.proto.Platform\x12\x0f\n\x07version\x18\x03 \x01(\tJ\x04\x08\x02\x10\x03*\xb6\x03\n\x0eRequestContext\x12\x17\n\x13\x43ONTEXT_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x43ONTEXT_PAGE_NAVIGATION\x10\x02\x12#\n\x1f\x43ONTEXT_BATCH_UPDATE_GOOGLE_SRP\x10\x04\x12$\n CONTEXT_BATCH_UPDATE_ACTIVE_TABS\x10\x05\x12\x1f\n\x1b\x43ONTEXT_BATCH_UPDATE_MODELS\x10\x06\x12\x15\n\x11\x43ONTEXT_BOOKMARKS\x10\x07\x12\x14\n\x10\x43ONTEXT_JOURNEYS\x10\x08\x12\x18\n\x14\x43ONTEXT_NEW_TAB_PAGE\x10\t\x12\x1d\n\x19\x43ONTEXT_PAGE_INSIGHTS_HUB\x10\x0b\x12.\n*CONTEXT_NON_PERSONALIZED_PAGE_INSIGHTS_HUB\x10\x0c\x12\x14\n\x10\x43ONTEXT_SHOPPING\x10\r\x12\x15\n\x11\x43ONTEXT_SHOP_CARD\x10\x0e\x12\'\n#CONTEXT_GLIC_ZERO_STATE_SUGGESTIONS\x10\x0f\"\x04\x08\x01\x10\x01\"\x04\x08\x03\x10\x03\"\x04\x08\n\x10\n\"\x04\x08\x10\x10\x10*\xa3\x01\n\x08Platform\x12\x16\n\x12PLATFORM_UNDEFINED\x10\x00\x12\x14\n\x10PLATFORM_ANDROID\x10\x01\x12\x15\n\x11PLATFORM_CHROMEOS\x10\x02\x12\x10\n\x0cPLATFORM_IOS\x10\x03\x12\x12\n\x0ePLATFORM_LINUX\x10\x04\x12\x10\n\x0cPLATFORM_MAC\x10\x05\x12\x14\n\x10PLATFORM_WINDOWS\x10\x06\"\x04\x08\x07\x10\x07\x42M\n0org.chromium.components.optimization_guide.protoB\x10\x43ommonTypesProtoH\x03\x92\x03\x04\x10\x02 \x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.optimization_guide.proto.common_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n0org.chromium.components.optimization_guide.protoB\020CommonTypesProtoH\003\222\003\004\020\002 \003'
  _globals['_REQUESTCONTEXT']._serialized_start=358
  _globals['_REQUESTCONTEXT']._serialized_end=796
  _globals['_PLATFORM']._serialized_start=799
  _globals['_PLATFORM']._serialized_end=962
  _globals['_FIELDTRIAL']._serialized_start=84
  _globals['_FIELDTRIAL']._serialized_end=135
  _globals['_DURATION']._serialized_start=137
  _globals['_DURATION']._serialized_end=179
  _globals['_TIMESTAMP']._serialized_start=181
  _globals['_TIMESTAMP']._serialized_end=224
  _globals['_ANY']._serialized_start=226
  _globals['_ANY']._serialized_end=264
  _globals['_ORIGININFO']._serialized_start=266
  _globals['_ORIGININFO']._serialized_end=355
# @@protoc_insertion_point(module_scope)
