# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components/optimization_guide/proto/passage_embeddings_model_metadata.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'components/optimization_guide/proto/passage_embeddings_model_metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKcomponents/optimization_guide/proto/passage_embeddings_model_metadata.proto\x12\x18optimization_guide.proto\"~\n\x1ePassageEmbeddingsModelMetadata\x12 \n\x11input_window_size\x18\x01 \x01(\rB\x05\xaa\x01\x02\x08\x02\x12\x1a\n\x0boutput_size\x18\x02 \x01(\rB\x05\xaa\x01\x02\x08\x02\x12\x1e\n\x0fscore_threshold\x18\x03 \x01(\x01\x42\x05\xaa\x01\x02\x08\x02\x42\x02H\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components.optimization_guide.proto.passage_embeddings_model_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['input_window_size']._loaded_options = None
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['input_window_size']._serialized_options = b'\252\001\002\010\002'
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['output_size']._loaded_options = None
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['output_size']._serialized_options = b'\252\001\002\010\002'
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['score_threshold']._loaded_options = None
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA'].fields_by_name['score_threshold']._serialized_options = b'\252\001\002\010\002'
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA']._serialized_start=105
  _globals['_PASSAGEEMBEDDINGSMODELMETADATA']._serialized_end=231
# @@protoc_insertion_point(module_scope)
